#!/bin/bash

readonly ROOT_HOME='/root'
readonly ROOT_BASH_PROFILE_PATH="${ROOT_HOME}/.bash_profile"
readonly ROOT_PROFILE_PATH="${ROOT_HOME}/.profile"

if [ -f "${ROOT_BASH_PROFILE_PATH}" ]; then
	source "${ROOT_BASH_PROFILE_PATH}" >/dev/null 2>&1 || exit 200
elif [ -f "${ROOT_PROFILE_PATH}" ]; then
	source "${ROOT_PROFILE_PATH}" >/dev/null 2>&1 || exit 210
else
	exit 220
fi

#アップデータ
readonly UPDATOR="freshclam"
readonly UPDATOR_SERVICE="clamav-${UPDATOR}"

#スキャナ
readonly SCANNER="clamscan"

#サービスが起動中のステータスをあらわす文字列。
readonly STATUS_ACTIVE="active"

#サービスが停止中のステータスをあらわす文字列。
readonly STATUS_INACTIVE="inactive"

#サービスが有効の時の文字列。
readonly STATUS_ENABLED="enabled"

# rootのcrontabに起動設定を書くなどして、rootで動くようにしないとログが残らない。

#このスクリプトの名前。
readonly MY_NAME=$(basename "${0}")

#ロックファイルのパス
readonly _lockfile="/tmp/${MY_NAME}.lock"

function is_numeric() {
	local -r INPUT_VALUE="${1}"
	expr "${INPUT_VALUE}" + 1 >/dev/null 2>&1
	local -r ret="${?}"
	if [ "${ret}" -ge 2 ]; then
		return "${ret}"
	fi
	return 0
}

function delete_lock_file_and_exit() {
	local -r EXIT_CODE="${1}"
	is_numeric "${EXIT_CODE}"
	local -r ret="${?}"
	if [ "${ret}" -ge 2 ]; then
		echo "指定された戻り値が数字ではない。戻り値=${EXIT_CODE}"1 >&2
		exit 100
	fi
	if [ -h "${_lockfile}" ]; then
		if ! rm -f "${_lockfile}" >/dev/null 2>&1; then
			echo "ロックファイル削除失敗。戻り値はrmのものになる。ロックファイル=${_lockfile}"1 >&2
			exit "${?}"
		fi
	fi
	exit "${EXIT_CODE}"
}

function delete_lock_and_exit() {
	local -r YMD_VAL=$(date +%Y%m%d%H%M%S)
	echo "${YMD_VAL}_${1}_${3}" >>"${2}"
	delete_lock_file_and_exit "${3}"
}

function usage_exit() {
	echo 'Usage: $0 [-f] [-d (1-24)] ' 1>&2
	echo 'fleshclamとclamscanを実行する' 1>&2
	echo '-f 設定(多重起動防止と実行時間の制限を無視する。)' 1>&2
	echo '-d このスクリプトが実行された時間がこのオプションで指定された値で割り切れる場合にのみウイルススキャンを行う。規定値は1。範囲は1-24。' 1>&2
	exit 1
}

function wait_2_min() {
	sleep 120
}

function systemd_service_start_stop() {
	local -r TARGET_SERVICE_NAME="${1}"
	local -r EXPECTED_TAREGT_SERVICE_STATUS_BEFORE_OPERATION="${2}"
	local -r SYSTEMCTL_OPERATION="${3}"
	local -r EXPECTED_TAREGT_SERVICE_STATUS_AFTER_OPERATION="${4}"
	local -r EXIT_CODE_NUM="${5}"

	is_numeric "${EXIT_CODE_NUM}"
	local -r ret="${?}"
	if [ "${ret}" -ge 2 ]; then
		echo "$(date +%Y%m%d%H%M%S)_EXIT_CODE_NUM_${EXIT_CODE_NUM}が数値ではありません。終了します。"
		delete_lock_file_and_exit 10
	fi
	if [ "${EXPECTED_TAREGT_SERVICE_STATUS_BEFORE_OPERATION}" != "${STATUS_ACTIVE}" ] && [ "${EXPECTED_TAREGT_SERVICE_STATUS_BEFORE_OPERATION}" != "${STATUS_INACTIVE}" ]; then
		echo "$(date +%Y%m%d%H%M%S)_EXPECTED_TAREGT_SERVICE_STATUS_BEFORE_OPERATION_${EXPECTED_TAREGT_SERVICE_STATUS_BEFORE_OPERATION}が想定外の値です。終了します。"
		delete_lock_file_and_exit 10
	fi
	if [ "${EXPECTED_TAREGT_SERVICE_STATUS_AFTER_OPERATION}" != "${STATUS_ACTIVE}" ] && [ "${EXPECTED_TAREGT_SERVICE_STATUS_AFTER_OPERATION}" != "${STATUS_INACTIVE}" ]; then
		echo "$(date +%Y%m%d%H%M%S)_EXPECTED_TAREGT_SERVICE_STATUS_AFTER_OPERATION_${EXPECTED_TAREGT_SERVICE_STATUS_AFTER_OPERATION}が想定外の値です。終了します。"
		delete_lock_file_and_exit 10
	fi

	local -r TARGET_SERVICE_ENABLED=$(systemctl is-enabled "${TARGET_SERVICE_NAME}")
	if [ "${TARGET_SERVICE_ENABLED}" = "${STATUS_ENABLED}" ]; then
		local -r B_STAT=$(systemctl show -p ActiveState "${TARGET_SERVICE_NAME}")
		local -r TARGET_SERVICE_STATUS_BEFORE_OPERATION="${B_STAT#*=}"
		echo "$(date +%Y%m%d%H%M%S)_${TARGET_SERVICE_NAME}の状態(処理前) = ${TARGET_SERVICE_STATUS_BEFORE_OPERATION} 処理=${SYSTEMCTL_OPERATION}"
		if [ "${TARGET_SERVICE_STATUS_BEFORE_OPERATION}" = "${EXPECTED_TAREGT_SERVICE_STATUS_BEFORE_OPERATION}" ]; then
			systemctl "${SYSTEMCTL_OPERATION}" "${TARGET_SERVICE_NAME}"
			wait_2_min
			local -r A_STAT=$(systemctl show -p ActiveState "${TARGET_SERVICE_NAME}")
			local -r TARGET_SERVICE_STATUS_AFTER_OPERATION="${A_STAT#*=}"
			echo "$(date +%Y%m%d%H%M%S)_${TARGET_SERVICE_NAME}の状態(処理後) = ${TARGET_SERVICE_STATUS_AFTER_OPERATION}"
			if [ "${TARGET_SERVICE_STATUS_AFTER_OPERATION}" != "${EXPECTED_TAREGT_SERVICE_STATUS_AFTER_OPERATION}" ]; then
				echo "$(date +%Y%m%d%H%M%S)_${TARGET_SERVICE_NAME}が期待されない状態です。状態=${TARGET_SERVICE_STATUS_AFTER_OPERATION} 期待=${EXPECTED_TAREGT_SERVICE_STATUS_AFTER_OPERATION} 終了します。"
				delete_lock_file_and_exit "${EXIT_CODE_NUM}"
			fi
		fi
	fi
	return 0
}

function stop_systemd_service() {
	local -r TARGET_SERVICE_NAME="${1}"
	local -r EXIT_CODE_NUM="${2}"
	systemd_service_start_stop "${TARGET_SERVICE_NAME}" "${STATUS_ACTIVE}" 'stop' "${STATUS_INACTIVE}" "${EXIT_CODE_NUM}"
}

function restart_systemd_service() {
	local -r TARGET_SERVICE_NAME="${1}"
	local -r EXIT_CODE_NUM="${2}"
	systemd_service_start_stop "${TARGET_SERVICE_NAME}" "${STATUS_INACTIVE}" 'restart' "${STATUS_ACTIVE}" "${EXIT_CODE_NUM}"
}

ENABLE_f="f"
DEV_OPTARG="1"

while getopts "fd:" OPT; do
	case $OPT in
	f)
		ENABLE_f="t"
		;;
	d)
		DEV_OPTARG="${OPTARG}"
		;;
	: | \?)
		usage_exit
		;;
	esac
done

shift $((OPTIND - 1))

readonly LOGDIR="/var/log/clamav-scan-log"
readonly LOGFILE="${LOGDIR}/$(date +%Y%m%d%H%M%S).log"
mkdir -p "${LOGDIR}" && chmod 755 "${LOGDIR}"

echo "$(date +%Y%m%d%H%M%S)_開始します。" >>"${LOGFILE}"

is_numeric "${DEV_OPTARG}"
readonly RET_DEV_OPTARG_ISNUMERIC="${?}"
if [ "${RET_DEV_OPTARG_ISNUMERIC}" -ge 2 ] || [ "${DEV_OPTARG}" -lt 1 ] || [ "${DEV_OPTARG}" -gt 24 ]; then
	echo "$(date +%Y%m%d%H%M%S)_-dオプションで取得した値が異常です。取得した値=${DEV_OPTARG}" >>"${LOGFILE}"
	usage_exit
fi

readonly ISODIR="/var/lib/clamav/quarantine"

mkdir -p "${ISODIR}"
chmod 700 "${ISODIR}"
chown root:root "${ISODIR}"

# 除外パスリストの読み込み。
#ディレクトリは末尾に/。
#ファイルは末尾に/なし。
readonly EXCLUDELIST="/etc/clamscan.exclude"
EXCLUDEOPT=()
if [ -s "${EXCLUDELIST}" ]; then
	EXCLUDEOPT[1]="--exclude-dir=^$ISODIR"
	for i in $(cat "${EXCLUDELIST}"); do
		if [ "$(echo "${i}" | grep \/$)" ]; then
			i=$(echo "${i}" | sed -e 's/^\([^ ]*\)\/$/\1/p' -e d)
			EXCLUDEOPT+=("--exclude-dir=^${i}")
		else
			EXCLUDEOPT+=("--exclude=${i}")
		fi
	done
fi

if [ "${ENABLE_f}" = "t" ]; then
	echo "$(date +%Y%m%d%H%M%S)_-fオプションが有効です。" >>"${LOGFILE}"
	if [ -f "${_lockfile}" ]; then
		echo "$(date +%Y%m%d%H%M%S)_ロックファイルを強制的に削除し、処理を継続します。" >>"${LOGFILE}"
		rm -f "${_lockfile}" >>"${LOGFILE}" 2>&1
		echo "$(date +%Y%m%d%H%M%S)_ロックファイルを強制的に削除しました。結果にかかわらず処理を続行します。" >>"${LOGFILE}"
	fi
fi

#ロックファイル生成。
echo "$(date +%Y%m%d%H%M%S)_ロックファイル生成。" >>"${LOGFILE}"
ln -s /dummy "${_lockfile}" >/dev/null 2>&1 || {
	echo "$(date +%Y%m%d%H%M%S)_Cannot run multiple instance." >>"${LOGFILE}"
	#他のプロセスが起動中なのでロックファイルは削除しない。
	exit 110
}

trap 'rm "${_lockfile}"; exit' SIGHUP SIGINT SIGQUIT SIGTERM

echo "$(date +%Y%m%d%H%M%S)_実行間隔制限判定開始。" >>"${LOGFILE}"
if [ "${ENABLE_f}" != "t" ]; then
	#今の時間(何時?)
	NowHour=$(date +%-H)
	#割る数
	readonly Dev="${DEV_OPTARG}"

	echo "now=${NowHour}" >>"${LOGFILE}"
	echo "dev=${Dev}" >>"${LOGFILE}"

	mod="$((${NowHour} % ${Dev}))"
	#制限が有効で、割る数で割り切れない時間なら起動しない。
	if [ ! "0" -eq ${mod} ]; then
		delete_lock_and_exit "起動間隔を制限しています。この時間は終了します。" "${LOGFILE}" 10
	fi
else
	echo "$(date +%Y%m%d%H%M%S)_-fオプションが有効です。" >>"${LOGFILE}"
fi

# ファイル更新日時が5000日を越えたログファイルを削除
echo "$(date +%Y%m%d%H%M%S)_旧ログ削除。" >>"${LOGFILE}"
readonly PARAM_DATE_NUM=5000
find "${LOGDIR}" -name "*.log" -type f -mtime +"${PARAM_DATE_NUM}" -exec rm -f {} \;

#freshclamがサービスになっていた場合は一旦停止する。
echo "$(date +%Y%m%d%H%M%S)_DBアップデートサービス停止。" >>"${LOGFILE}"
stop_systemd_service "${UPDATOR_SERVICE}" 11 >>"${LOGFILE}" 2>&1

#制限が有効で、clamscanもしくはfreshclamが既に実行中だった場合、起動しない。
echo "$(date +%Y%m%d%H%M%S)_プロセス確認。" >>"${LOGFILE}"
if [ "${ENABLE_f}" != "t" ]; then
	readonly UP_LIST=$(pgrep -l "${UPDATOR}" | grep -v grep | grep -v "${MY_NAME}")
	readonly UP_COUNT=$(echo "${UP_LIST}" | grep -v '^\s*$' | wc -l)
	#echo "UL_${UP_LIST}_UC_${UP_COUNT}" >>"${LOGFILE}"
	if [ "${UP_COUNT}" != 0 ]; then
		delete_lock_and_exit "${UPDATOR}が起動中です。終了します。" "${LOGFILE}" 12
	fi
	readonly SCAN_LIST=$(pgrep -l "${SCANNER}" | grep -v grep | grep -v "${MY_NAME}")
	readonly SCAN_COUNT=$(echo "${SCAN_LIST}" | grep -v '^\s*$' | wc -l)
	#echo "SL_${SCAN_LIST}_SC_${SCAN_COUNT}" >>"${LOGFILE}"
	if [ "${SCAN_COUNT}" != 0 ]; then
		delete_lock_and_exit "${SCANNER}が起動中です。終了します。" "${LOGFILE}" 13
	fi
else
	echo "$(date +%Y%m%d%H%M%S)_-fオプションが有効です。" >>"${LOGFILE}"
fi

echo "$(date +%Y%m%d%H%M%S)_DB更新。" >>"${LOGFILE}"
# DB update
# epelからインストールの場合、freshclamのインストール時に、3時間ごとの自動更新(freshclam-sleep)が登録されるのであまり意味が無いが、念のため。
${UPDATOR} >>"${LOGFILE}" 2>&1
readonly RET_FRESHCLAM="${?}"
if [ "${RET_FRESHCLAM}" -ne 0 ]; then
	delete_lock_and_exit "freshclamの戻り値が${RET_FRESHCLAM}です。終了します。" "${LOGFILE}" 14
fi

#freshclamがサービスになっていた場合は再起動する。
echo "$(date +%Y%m%d%H%M%S)_DBアップデートサービス起動。" >>"${LOGFILE}"
restart_systemd_service "${UPDATOR_SERVICE}" 15 >>"${LOGFILE}" 2>&1

#clamdのメモリ消費量が大きいので、スキャン中はオンアクセススキャンを停止する。
#サービスが有効では無い場合は何もしない。

readonly ON_ACCESS_SCAN_SERVICE='clamonacc'
readonly CLAMD_SERVICE='clamd@scan'

echo "$(date +%Y%m%d%H%M%S)_オンアクセススキャンを停止する。" >>"${LOGFILE}"
stop_systemd_service "${ON_ACCESS_SCAN_SERVICE}" 16 >>"${LOGFILE}" 2>&1
stop_systemd_service "${CLAMD_SERVICE}" 17 >>"${LOGFILE}" 2>&1
echo "$(date +%Y%m%d%H%M%S)_オンアクセススキャンの停止を完了。" >>"${LOGFILE}"

echo "$(date +%Y%m%d%H%M%S)_スキャン開始。" >>"${LOGFILE}"
# virus scan
#感染したファイルのみログに記載する。
#感染したファイルは隔離する。
readonly _NICE_ARGS=("-n" "20" "${SCANNER}" "/" "-r" "--infected" "--move=${ISODIR}")
readonly NICE_ARGS=("${_NICE_ARGS[@]}" "${EXCLUDEOPT[@]}")
nice "${NICE_ARGS[@]}" >>"${LOGFILE}" 2>&1

readonly RET_CLAMSCAN="${?}"
if [ "${RET_CLAMSCAN}" -ne 0 ]; then
	echo "$(date +%Y%m%d%H%M%S)_clamscanの戻り値が${RET_CLAMSCAN}です。" >>"${LOGFILE}"
fi
echo "$(date +%Y%m%d%H%M%S)_スキャン終了。" >>"${LOGFILE}"

#再開の際は、ステータスがactiveでないなら再始動を試みる。

echo "$(date +%Y%m%d%H%M%S)_オンアクセススキャンを再開する。" >>"${LOGFILE}"
restart_systemd_service "${CLAMD_SERVICE}" 18 >>"${LOGFILE}" 2>&1
restart_systemd_service "${ON_ACCESS_SCAN_SERVICE}" 19 >>"${LOGFILE}" 2>&1

echo "$(date +%Y%m%d%H%M%S)_オンアクセススキャンの再開を完了。" >>"${LOGFILE}"

#ログファイルの内容を表示
cat "${LOGFILE}"

delete_lock_and_exit "正常終了します。" "${LOGFILE}" 0
